tunnel: 173e5515-cdf3-4140-b8c4-ad87bf3737df
credentials-file: /Users/pranavgupta/.cloudflared/173e5515-cdf3-4140-b8c4-ad87bf3737df.json

ingress:
  - hostname: dev.pharmagpt.co
    service: http://127.0.0.1:5173
  - service: http_status:404
