tunnel: invoice-app
credentials-file: /Users/pranavgupta/.cloudflared/87f642ac-94bc-406d-a86c-bf08e829789a.json 

ingress:
  - hostname: pharmagpt.co
    service: http://127.0.0.1:5173
  - hostname: www.pharmagpt.co
    service: http://127.0.0.1:5173
  - hostname: api.pharmagpt.co
    service: http://127.0.0.1:8000
  - service: http_status:404
