version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ..:/workspaces/Invoice-Extractor:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Connect to the same network as the database
    depends_on:
      - db

    # Environment variables for the container
    environment:
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password

  db:
    image: neo4j:5.26.0
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
